name: Build docker image

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
      packages: write
    
    steps:
      - uses: actions/checkout@v3
      
      - name: QEMU Setup
        uses: docker/setup-qemu-action@v2
      
      - name: Docker Setup
        uses: docker/setup-buildx-action@v2
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/z1_fibo
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          cache-from: type=registry,ref=docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/fibo_z1/z1_fibo:buildx-cache
          cache-to: type=registry,ref=docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/fibo_z1/z1_fibo:buildx-cache
          platforms: linux/amd64,linux/arm64
          context: ./
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
